<a href="https://colab.research.google.com/github/SnehaDharne/GDM-diagnosis/blob/main/Imputations_with_RF_and_LR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
path='/content/drive/MyDrive/datasets for colab/pima-indians-diabetes.csv'

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv(path)

In [ ]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
# make age category column which will help age-appropriate in filling values which are 0
df['age_category'] = pd.cut(df['Age'], bins=[0, 21, 31, 41, 51, 61, 71, 81, np.inf], labels=[1,2,3,4,5,6,7,8])
df['age_category'] = df['age_category'].astype(int)
agecat = [1,2,3,4,5,6,7,8]

MEAN

In [ ]:
features = ['Glucose', 'BloodPressure', 'SkinThickness', 'BMI','Insulin']
for feature in features:
  for agec in agecat:
        if df[feature].dtype == 'float64':
            df[feature].replace(0, round(df[df['age_category'] == agec][feature].mean(), 1), inplace=True)
        else:
            df[feature].replace(0, round(df[df['age_category'] == agec][feature].mean(), 0), inplace=True)

In [ ]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  121.597656      72.113281      26.152344  115.835938   
std       3.369578   30.455873      12.169980       9.938479   94.298227   
min       0.000000   44.000000      24.000000       7.000000   14.000000   
25%       1.000000   99.750000      64.000000      19.000000   74.000000   
50%       3.000000  117.000000      72.000000      23.000000   74.000000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  \
count  768.000000                768.000000  768.000000  768.000000   
mean    32.390755                  0.471876   33.240885    0.348958   
std      6.897416                  0.331329   11.760232    0.476951   
min     18.200000                  0.078000   21.000000    0.000000   
25%     27.500000                  0.243750   24.000000    0.000000   
50%     32.000000                  0.372500   29.000000    0.000000   
75%     36.600000                  0.626250   41.000000    1.000000   
max     67.100000                  2.420000   81.000000    1.000000   

       age_category  
count    768.000000  
mean       2.697917  
std        1.192062  
min        1.000000  
25%        2.000000  
50%        2.000000  
75%        3.000000  
max        7.000000

In [ ]:
from scipy import stats
import numpy as np
z= np.abs(stats.zscore(df))
print(z)

     Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0       0.639947  0.867470       0.009314       0.890823  0.443945  0.175433   
1       0.844885  1.202445       0.502652       0.286715  0.443945  0.840101   
2       1.233880  2.017422       0.667098       0.720131  0.443945  1.318853   
3       0.844885  1.071022       0.502652       0.317392  0.231713  0.622487   
4       1.141852  0.506056       2.640449       0.890823  0.553542  1.553658   
..           ...       ...            ...            ...       ...       ...   
763     1.827813  0.676752       0.319577       2.199722  0.680881  0.073879   
764     0.547919  0.013219       0.173760       0.085346  0.443945  0.639677   
765     0.342981  0.019636       0.009314       0.317392  0.040705  0.898132   
766     0.844885  0.144642       0.995990       0.720131  0.443945  0.332334   
767     0.844885  0.939599       0.173760       0.488084  0.443945  0.288811   

     DiabetesPedigreeFunction       Age

In [ ]:
threshold = 3
print(np.where(z>3))

(array([  4,   8,  13,  18,  43,  45,  57,  58,  88, 106, 111, 120, 120,
       123, 125, 125, 153, 159, 177, 177, 186, 220, 228, 228, 247, 248,
       286, 298, 330, 370, 370, 371, 392, 395, 409, 415, 445, 445, 445,
       453, 453, 455, 459, 459, 486, 549, 579, 584, 593, 597, 621, 645,
       655, 666, 673, 684, 691, 695, 753]), array([6, 4, 4, 2, 2, 6, 3, 6, 0, 2, 4, 3, 5, 7, 2, 5, 4, 0, 2, 5, 4, 4,
       4, 6, 4, 4, 4, 0, 6, 4, 6, 6, 4, 6, 4, 4, 3, 5, 6, 7, 9, 0, 7, 9,
       4, 2, 3, 4, 6, 2, 6, 4, 4, 7, 5, 7, 2, 4, 4]))


In [ ]:
df = df[(z < 3).all(axis=1)]

In [ ]:
q1 = df.quantile(0.25)
q3 = df.quantile(0.75)
iqr= q3-q1
print(iqr)

Pregnancies                  5.0000
Glucose                     39.0000
BloodPressure               16.0000
SkinThickness               13.0000
Insulin                     46.0000
BMI                          8.7000
DiabetesPedigreeFunction     0.3585
Age                         16.0000
Outcome                      1.0000
age_category                 1.0000
dtype: float64


In [ ]:
df = df[~((df <(q1 - 1.5 * iqr))|(df>(q3+1.5*iqr))).any(axis=1)]
df.shape

(554, 10)

In [ ]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   554.000000  554.000000     554.000000     554.000000  554.000000   
mean      3.601083  114.940433      70.815884      24.835740   86.494585   
std       3.152208   27.290846      10.813328       8.665791   32.635321   
min       0.000000   44.000000      44.000000       8.000000   15.000000   
25%       1.000000   96.000000      64.000000      19.000000   74.000000   
50%       3.000000  111.000000      70.000000      20.500000   74.000000   
75%       6.000000  129.000000      78.000000      31.000000   92.000000   
max      13.000000  196.000000     104.000000      50.000000  188.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  \
count  554.000000                554.000000  554.000000  554.000000   
mean    31.546209                  0.404964   30.166065    0.292419   
std      6.209230                  0.231664    8.300496    0.455285   
min     18.200000                  0.078000   21.000000    0.000000   
25%     27.300000                  0.236000   23.000000    0.000000   
50%     31.200000                  0.336500   28.000000    0.000000   
75%     35.400000                  0.546500   37.000000    1.000000   
max     48.300000                  1.136000   51.000000    1.000000   

       age_category  
count    554.000000  
mean       2.386282  
std        0.836915  
min        1.000000  
25%        2.000000  
50%        2.000000  
75%        3.000000  
max        4.000000

In [ ]:
from sklearn.model_selection import train_test_split
X = df.drop(['Outcome'], axis=1)
y = df['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
#RandomClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=300, bootstrap = True, max_features ='sqrt')
rf.fit(X_train, y_train)

RandomForestClassifier(max_features='sqrt', n_estimators=300)

In [ ]:
y_pred =rf.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, classification_report
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
model_mse = mean_squared_error(y_pred, y_test)
print(model_mse)
print(classification_report(y_test, y_pred))

[[72  7]
 [15 17]]
Accuracy: 0.8018018018018018
0.1981981981981982
              precision    recall  f1-score   support

           0       0.83      0.91      0.87        79
           1       0.71      0.53      0.61        32

    accuracy                           0.80       111
   macro avg       0.77      0.72      0.74       111
weighted avg       0.79      0.80      0.79       111



In [ ]:
#LogisticRegression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=5000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=5000)

In [ ]:
y_pred =lr.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, classification_report
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
model_mse = mean_squared_error(y_pred, y_test)
print(model_mse)
print(classification_report(y_test, y_pred))

[[77  2]
 [18 14]]
Accuracy: 0.8198198198198198
0.18018018018018017
              precision    recall  f1-score   support

           0       0.81      0.97      0.89        79
           1       0.88      0.44      0.58        32

    accuracy                           0.82       111
   macro avg       0.84      0.71      0.73       111
weighted avg       0.83      0.82      0.80       111



MEDIAN

In [ ]:
df=pd.read_csv(path)
# make age category column which will help age-appropriate in filling values which are 0
df['age_category'] = pd.cut(df['Age'], bins=[0, 21, 31, 41, 51, 61, 71, 81, np.inf], labels=[1,2,3,4,5,6,7,8])
df['age_category'] = df['age_category'].astype(int)
agecat = [1,2,3,4,5,6,7,8]


features = ['Glucose', 'BloodPressure', 'SkinThickness', 'BMI','Insulin']
for feature in features:
  for agec in agecat:
        if df[feature].dtype == 'float64':
            df[feature].replace(0, round(df[df['age_category'] == agec][feature].median(), 1), inplace=True)
        else:
            df[feature].replace(0, round(df[df['age_category'] == agec][feature].median(), 0), inplace=True)




from scipy import stats
import numpy as np
z= np.abs(stats.zscore(df))

threshold = 3

df = df[(z < 3).all(axis=1)]

q1 = df.quantile(0.25)
q3 = df.quantile(0.75)
iqr= q3-q1

print(iqr)

Pregnancies                  5.000
Glucose                     39.000
BloodPressure               16.000
SkinThickness               12.000
Insulin                     80.000
BMI                          8.700
DiabetesPedigreeFunction     0.358
Age                         16.000
Outcome                      1.000
age_category                 1.000
dtype: float64


In [ ]:
df = df[~((df <(q1 - 1.5 * iqr))|(df>(q3+1.5*iqr))).any(axis=1)]
df.shape

(587, 10)

In [ ]:
from sklearn.model_selection import train_test_split
X = df.drop(['Outcome'], axis=1)
y = df['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)



In [ ]:
#RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=300, bootstrap = True, max_features ='sqrt')
rf.fit(X_train, y_train)
y_pred =rf.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
model_mse = mean_squared_error(y_pred, y_test)
print(model_mse)

[[72 10]
 [13 23]]
Accuracy: 0.8050847457627118
0.19491525423728814


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.88      0.86        82
           1       0.70      0.64      0.67        36

    accuracy                           0.81       118
   macro avg       0.77      0.76      0.76       118
weighted avg       0.80      0.81      0.80       118



In [ ]:
#LogisticRegression

In [ ]:
from sklearn.model_selection import train_test_split
X = df.drop(['Outcome'], axis=1)
y = df['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=5000)
lr.fit(X_train, y_train)



LogisticRegression(max_iter=5000)

In [ ]:
y_pred =lr.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
model_mse = mean_squared_error(y_pred, y_test)
print(model_mse)
print(classification_report(y_test, y_pred))

[[71 11]
 [13 23]]
Accuracy: 0.7966101694915254
0.2033898305084746
              precision    recall  f1-score   support

           0       0.85      0.87      0.86        82
           1       0.68      0.64      0.66        36

    accuracy                           0.80       118
   macro avg       0.76      0.75      0.76       118
weighted avg       0.79      0.80      0.79       118



DROP

In [ ]:
df=pd.read_csv(path)
features = ['Glucose', 'BloodPressure', 'SkinThickness', 'BMI','Insulin']
for feature in features:
  df = df[df[feature] != 0]

df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   392.000000  392.000000     392.000000     392.000000  392.000000   
mean      3.301020  122.627551      70.663265      29.145408  156.056122   
std       3.211424   30.860781      12.496092      10.516424  118.841690   
min       0.000000   56.000000      24.000000       7.000000   14.000000   
25%       1.000000   99.000000      62.000000      21.000000   76.750000   
50%       2.000000  119.000000      70.000000      29.000000  125.500000   
75%       5.000000  143.000000      78.000000      37.000000  190.000000   
max      17.000000  198.000000     110.000000      63.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  392.000000                392.000000  392.000000  392.000000  
mean    33.086224                  0.523046   30.864796    0.331633  
std      7.027659                  0.345488   10.200777    0.471401  
min     18.200000                  0.085000   21.000000    0.000000  
25%     28.400000                  0.269750   23.000000    0.000000  
50%     33.200000                  0.449500   27.000000    0.000000  
75%     37.100000                  0.687000   36.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
df=pd.read_csv(path)

features = ['Glucose', 'BloodPressure', 'SkinThickness', 'BMI','Insulin']
for feature in features:
  df = df[df[feature] != 0]




from scipy import stats
import numpy as np
z= np.abs(stats.zscore(df))

threshold = 3

df = df[(z < 3).all(axis=1)]

q1 = df.quantile(0.25)
q3 = df.quantile(0.75)
iqr= q3-q1


df = df[~((df <(q1 - 1.5 * iqr))|(df>(q3+1.5*iqr))).any(axis=1)]



In [ ]:
#RandomForest

In [ ]:
from sklearn.model_selection import train_test_split
X = df.drop(['Outcome'], axis=1)
y = df['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=300, bootstrap = True, max_features ='sqrt')
rf.fit(X_train, y_train)

y_pred =rf.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
from sklearn.metrics import mean_squared_error
model_mse = mean_squared_error(y_pred, y_test)
print(model_mse)

print(classification_report(y_test, y_pred))

[[44  3]
 [ 9  9]]
Accuracy: 0.8153846153846154
0.18461538461538463
              precision    recall  f1-score   support

           0       0.83      0.94      0.88        47
           1       0.75      0.50      0.60        18

    accuracy                           0.82        65
   macro avg       0.79      0.72      0.74        65
weighted avg       0.81      0.82      0.80        65



In [ ]:
#LogisticRegression

In [ ]:
from sklearn.model_selection import train_test_split
X = df.drop(['Outcome'], axis=1)
y = df['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=5000)
lr.fit(X_train, y_train)

y_pred =rf.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
from sklearn.metrics import mean_squared_error
model_mse = mean_squared_error(y_pred, y_test)
print(model_mse)

print(classification_report(y_test, y_pred))

[[44  3]
 [ 9  9]]
Accuracy: 0.8153846153846154
0.18461538461538463
              precision    recall  f1-score   support

           0       0.83      0.94      0.88        47
           1       0.75      0.50      0.60        18

    accuracy                           0.82        65
   macro avg       0.79      0.72      0.74        65
weighted avg       0.81      0.82      0.80        65



Most Frequent

In [ ]:
df=pd.read_csv(path)
from sklearn.impute import SimpleImputer

# For all readings == 0, impute with mean
fill_0 = SimpleImputer(missing_values=0,strategy="most_frequent")

from sklearn.model_selection import train_test_split
y = df['Outcome']
X = df.drop(['Outcome'], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
X_train= fill_0.fit_transform(X_train)
X_test = fill_0.fit_transform(X_test)

In [ ]:
#Random FOrest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=300, bootstrap = True, max_features ='sqrt')
rf.fit(X_train, y_train)

y_pred =rf.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
from sklearn.metrics import mean_squared_error
model_mse = mean_squared_error(y_pred, y_test)
print(model_mse)

print(classification_report(y_test, y_pred))

[[84 16]
 [23 31]]
Accuracy: 0.7467532467532467
0.2532467532467532
              precision    recall  f1-score   support

           0       0.79      0.84      0.81       100
           1       0.66      0.57      0.61        54

    accuracy                           0.75       154
   macro avg       0.72      0.71      0.71       154
weighted avg       0.74      0.75      0.74       154



In [ ]:
#LogisticRegression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=5000)
lr.fit(X_train, y_train)


LogisticRegression(max_iter=5000)

In [ ]:
y_pred =lr.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
from sklearn.metrics import mean_squared_error
model_mse = mean_squared_error(y_pred, y_test)
print(model_mse)

print(classification_report(y_test, y_pred))

[[81  5]
 [18 20]]
Accuracy: 0.8145161290322581
0.18548387096774194
              precision    recall  f1-score   support

           0       0.82      0.94      0.88        86
           1       0.80      0.53      0.63        38

    accuracy                           0.81       124
   macro avg       0.81      0.73      0.76       124
weighted avg       0.81      0.81      0.80       124



/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


Iterative Imputer

In [ ]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imp_mean = IterativeImputer(random_state=0)
imp_mean.fit(df)
x=imp_mean.transform(df)
#df_temp_knn = pd.DataFrame(imputed_data)
df_temp = pd.DataFrame(x)
#df_temp_knn.columns = df.columns
df_temp

0      1     2     3      4     5      6     7    8    9
0    6.0  148.0  72.0  35.0    0.0  33.6  0.627  50.0  1.0  4.0
1    1.0   85.0  66.0  29.0    0.0  26.6  0.351  31.0  0.0  2.0
2    8.0  183.0  64.0   0.0    0.0  23.3  0.672  32.0  1.0  3.0
3    1.0   89.0  66.0  23.0   94.0  28.1  0.167  21.0  0.0  1.0
4    5.0  116.0  74.0   0.0    0.0  25.6  0.201  30.0  0.0  2.0
..   ...    ...   ...   ...    ...   ...    ...   ...  ...  ...
570  9.0   89.0  62.0   0.0    0.0  22.5  0.142  33.0  0.0  3.0
571  2.0  122.0  70.0  27.0    0.0  36.8  0.340  27.0  0.0  2.0
572  5.0  121.0  72.0  23.0  112.0  26.2  0.245  30.0  0.0  2.0
573  1.0  126.0  60.0   0.0    0.0  30.1  0.349  47.0  1.0  4.0
574  1.0   93.0  70.0  31.0    0.0  30.4  0.315  23.0  0.0  2.0

[575 rows x 10 columns]

In [ ]:
df_temp.rename(columns = {0:'Pregnancies', 1:'GLucose',
                              2:'BloodPressure', 3:'SkinThickness', 4: 'Insulin', 5: 'BMI',6:'DiabetesPedigreeFunction',7:'Age',8:'Outcome',9:'Age_category'}, inplace = True)

In [ ]:
from scipy import stats
import numpy as np
z= np.abs(stats.zscore(df))

threshold = 3
print(np.where(z>3))

df = df[(z < 3).all(axis=1)]
q1 = df.quantile(0.25)
q3 = df.quantile(0.75)
iqr= q3-q1
print(iqr)

df = df[~((df <(q1 - 1.5 * iqr))|(df>(q3+1.5*iqr))).any(axis=1)]

(array([ 40, 306, 370]), array([4, 4, 6]))
Pregnancies                   5.00000
Glucose                      34.25000
BloodPressure                14.00000
SkinThickness                32.00000
Insulin                     116.00000
BMI                           8.52500
DiabetesPedigreeFunction      0.32275
Age                          14.00000
Outcome                       1.00000
age_category                  1.00000
dtype: float64


In [ ]:
from sklearn.model_selection import train_test_split
X = df.drop(['Outcome'], axis=1)
y = df['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
#Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=300, bootstrap = True, max_features ='sqrt')
rf.fit(X_train, y_train)
y_pred =rf.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, classification_report
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
model_mse = mean_squared_error(y_pred, y_test)
print("MSE:",model_mse)
print(classification_report(y_test, y_pred))

[[71  8]
 [16 14]]
Accuracy: 0.7798165137614679
MSE: 0.22018348623853212
              precision    recall  f1-score   support

           0       0.82      0.90      0.86        79
           1       0.64      0.47      0.54        30

    accuracy                           0.78       109
   macro avg       0.73      0.68      0.70       109
weighted avg       0.77      0.78      0.77       109



In [ ]:
#Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=5000)
lr.fit(X_train, y_train)
y_pred =lr.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, classification_report
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
model_mse = mean_squared_error(y_pred, y_test)
print("MSE:" ,model_mse)


[[75  4]
 [18 12]]
Accuracy: 0.7981651376146789
MSE: 0.2018348623853211


KNN IMPUTER

In [ ]:
df=pd.read_csv(path)
# make age category column which will help age-appropriate in filling values which are 0
df['age_category'] = pd.cut(df['Age'], bins=[0, 21, 31, 41, 51, 61, 71, 81, np.inf], labels=[1,2,3,4,5,6,7,8])
df['age_category'] = df['age_category'].astype(int)
agecat = [1,2,3,4,5,6,7,8]


from sklearn.impute import KNNImputer
imp_mean = KNNImputer()
imp_mean.fit(df)
x=imp_mean.transform(df)
df_temp = pd.DataFrame(x)
#df_temp_knn.columns = df.columns
df_temp

df_temp.rename(columns = {0:'Pregnancies', 1:'GLucose',
                              2:'BloodPressure', 3:'SkinThickness', 4: 'Insulin', 5: 'BMI',6:'DiabetesPedigreeFunction',7:'Age',8:'Outcome',9:'Age_category'}, inplace = True)

from scipy import stats
import numpy as np
z= np.abs(stats.zscore(df))

threshold = 3

df = df[(z < 3).all(axis=1)]

q1 = df.quantile(0.25)
q3 = df.quantile(0.75)
iqr= q3-q1

df = df[~((df <(q1 - 1.5 * iqr))|(df>(q3+1.5*iqr))).any(axis=1)]

from sklearn.model_selection import train_test_split
X = df.drop(['Outcome'], axis=1)
y = df['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)



In [ ]:
#RandomForest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=300, bootstrap = True, max_features ='sqrt')
rf.fit(X_train, y_train)
y_pred =rf.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, classification_report
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
model_mse = mean_squared_error(y_pred, y_test)
print("MSE:", model_mse)


[[75  6]
 [17 17]]
Accuracy: 0.8
MSE: 0.2


In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=5000)
lr.fit(X_train, y_train)
y_pred =lr.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, classification_report
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
model_mse = mean_squared_error(y_pred, y_test)
print("MSE:", model_mse)

[[74  7]
 [15 19]]
Accuracy: 0.808695652173913
MSE: 0.19130434782608696
